### ISSUE TITLE
Hackney dep too old

### ISSUE THREAD

**Issue by jalberto** [Rastopyr/tub_ex#4]
Hi,

after install I get this message:

```
  hackney 1.6.6 RETIRED!                       
    (invalid)
```

probably a soft dep upgrade must be enough to solve it.
Thanks!

**Comment by jalberto** [comment]
related: #5

**Comment by Rastopyr** [comment]
@jalberto thank you very much! PR is merged

**Comment by jalberto** [comment]
thank you!
